import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#161d19",
        "surface-container": "#1a211d",
        "on-primary-container": "#00422b",
        "on-error": "#690005",
        "on-primary-fixed": "#002113",
        "secondary-fixed-dim": "#bcc7de",
        "on-primary": "#003824",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-bright": "#343b36",
        "surface-tint": "#4edea3",
        "secondary-fixed": "#d8e3fa",
        "on-surface-variant": "#bbcabf",
        "on-surface": "#dde4dd",
        "emerald-glow": "#064e3b",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary-fixed-variant": "#005236",
        "outline-variant": "#3c4a42",
        "surface-variant": "#2f3632",
        "secondary-container": "#3c475a",
        "warning-amber": "#f59e0b",
        "primary-fixed": "#6ffbbe",
        "surface-dim": "#0e1511",
        "on-secondary": "#263143",
        "inverse-on-surface": "#2b322d",
        "surface-container-high": "#242c27",
        "on-secondary-fixed-variant": "#3c475a",
        "on-tertiary-fixed": "#2a1700",
        "primary-fixed-dim": "#4edea3",
        "inverse-surface": "#dde4dd",
        surface: "#0e1511",
        "tertiary-container": "#e29100",
        "error-container": "#93000a",
        tertiary: "#ffb95f",
        "on-secondary-fixed": "#111c2d",
        "on-tertiary": "#472a00",
        "surface-container-highest": "#2f3632",
        "error-red": "#ef4444",
        "hairline-border": "#334155",
        "surface-container-lowest": "#09100c",
        "elevated-card": "#1e293b",
        "on-secondary-container": "#aab5cc",
        background: "#0e1511",
        "tertiary-fixed": "#ffddb8",
        "inverse-primary": "#006c49",
        outline: "#86948a",
        "on-tertiary-container": "#523200",
        "on-background": "#dde4dd",
        "matte-canvas": "#0f1419",
        error: "#ffb4ab",
        secondary: "#bcc7de",
        "on-error-container": "#ffdad6",
        "primary-container": "#10b981",
        primary: "#4edea3",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "2rem",
        "margin-mobile": "1.25rem",
        "stack-md": "1rem",
        "touch-target": "3rem",
        gutter: "1rem",
        "stack-sm": "0.5rem",
        "margin-desktop": "2.5rem",
      },
      fontFamily: {
        body: ["Hanken Grotesk", "sans-serif"],
        headline: ["Hanken Grotesk", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
